apiVersion: v1
kind: PersistentVolume
metadata:
  name: teacheat-pv
  labels:
    type: local
    app: teacheat
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/vol/web/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teacheat-pvc
  labels:
    app: teacheat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: teacheat-service
  labels:
    app: teacheat
spec:
  ports:
    - port: 9000
  selector:
    app: teacheat
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: teacheat-deployment
  labels:
    app: teacheat

spec:
  selector:
    matchLabels:
      app: teacheat

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: teacheat

    spec:
      volumes:
        - name: teacheat-app-data
          persistentVolumeClaim:
            claimName: teacheat-pvc

      containers:
        - image: teacheat-app:latest
          imagePullPolicy: Never
          name: teacheat
          ports:
            - containerPort: 8000
              name: teacheat

          volumeMounts:
            - name: teacheat-app-data
              mountPath: /app/vol/web/

          env:
            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: app_port

            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: allowed_hosts

            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: debug

            - name: SQL_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: sql_debug

            - name: secure_browser_xss_filter
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: secure_ssl_redirect

            - name: SECURE_BROWSER_XSS_FILTER
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: secure_browser_xss_filter

            - name: SECURE_CONTENT_TYPE_NOSNIFF
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: secure_content_type_nosniff

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret_key

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres_db

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres_user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres_password

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_host

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db_port

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: redis_port


            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: redis_password

            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: celery_broker_url

            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: celery_result_backend

            - name: ADMIN_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: admin_url

            - name: ACCESS_TOKEN_LIFETIME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: access_token_lifetime




        - image: teacheat-proxy:latest
          imagePullPolicy: Never
          name: nginx
          ports:
            - containerPort: 9000
              name: proxy
          volumeMounts:
            - name: teacheat-app-data
              mountPath: /app/vol/web/
          env:
            - name: LISTEN_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: listen_port

            - name: APP_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: app_host

            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: app_port

            - name: CLIENT_MAX_BODY
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: client_max_body